add calendar
js-tasks-ru/htmlcss-20210812_boogie-woogie8 pull request #10
Opened 2021-08-27 20:58 UTC by ShakirovaAliya

2021-08-27 20:58 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-08-28 11:48 UTC, GSemikozov requested changes

2021-08-28 11:48 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    margin: 0 auto;
на уровне блока марджины и другие свойства для внешнего позиционирования не добавляем

2021-08-29 20:48 UTC, ShakirovaAliya commented on 05-lection3/03-calendar/calendar.css
> +    margin: 0 auto;
убрала марджины

2021-08-30 08:17 UTC, GSemikozov approved these changes

2021-08-30 08:17 UTC, merged