add avatar
js-tasks-ru/htmlcss-20210812_boogie-woogie8 pull request #14
Opened 2021-09-03 20:20 UTC by ShakirovaAliya

2021-09-03 20:21 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-04 15:54 UTC, GSemikozov requested changes

2021-09-04 15:54 UTC, GSemikozov commented on assets/css/main.css
> +    width: 1px;
отсюда и ниже - все это можно заменить на opacity: 0 + pointer-events: none + outline: none

2021-09-04 15:54 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +.avatar {
в целом, попытка сделать компонент аватара через использование input type=file очень похвально. Но - реализация подвела) В данном случае, насколько вижу по коду, компонент не соответствует дизайну и общей структуре разметки (ненужные тайтлы). Компонент на самом деле дожен состоять из обертки для картинки и самой картинки. Если хочется сохранить функционал выбора файла - тогда инпут так же прячем, но его надо обернуть в label. Сам label и будет иметь класс .avatar, а внутри - будет спрятанный инпут + картинка avatar__image

2021-09-05 10:49 UTC, ShakirovaAliya commented on assets/css/main.css
> +    width: 1px;
убрала

2021-09-05 10:50 UTC, ShakirovaAliya commented on 06-lection4/01-avatar/avatar.css
> +.avatar {
заменила на img

2021-09-05 10:54 UTC, GSemikozov requested changes

2021-09-05 10:54 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +    border-radius: 8px;
вот здесь думаю вообще никакие радиусы не нужны, как и бордеры и паддинги, а вместо комбинации width 100% + max-width 300px лучше явно задать фиксированные значения для ширины и высоты, можно даже в виде локальных css-переменных (в перспективе у компонента аватар может быть больше размеров, которыми можно будет управлять через модификаторы)

2021-09-05 10:54 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +    cursor: pointer;
курсор пусть болтается на родителе
и еще - нужно растянуть картинку по родителю (width + height 100%)

2021-09-05 11:02 UTC, ShakirovaAliya commented on 06-lection4/01-avatar/avatar.css
> +    border-radius: 8px;
исправила

2021-09-05 11:02 UTC, ShakirovaAliya commented on 06-lection4/01-avatar/avatar.css
> +    cursor: pointer;
исправила

2021-09-05 11:20 UTC, GSemikozov requested changes

2021-09-05 11:20 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +    --avatar-width: 160px;
можно перенести прямо в .avatar - эти переменные нужны только здесь, локально, не глобально )

2021-09-05 11:47 UTC, ShakirovaAliya commented on 06-lection4/01-avatar/avatar.css
> +    --avatar-width: 160px;
исправила

2021-09-05 11:50 UTC, GSemikozov approved these changes

2021-09-05 11:50 UTC, merged