add toggle
js-tasks-ru/htmlcss-20210812_boogie-woogie8 pull request #22
Opened 2021-09-05 14:29 UTC by ShakirovaAliya

2021-09-05 14:29 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-05 14:31 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-05 14:40 UTC, GSemikozov requested changes

2021-09-05 14:40 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +    content: "";
дублировать все свойства не нужно, только те которые меняем

2021-09-05 15:20 UTC, ShakirovaAliya commented on 07-lection5/03-toggler/toggler.css
> +    content: "";
исправила

2021-09-06 07:24 UTC, GSemikozov approved these changes

2021-09-06 07:24 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2021-09-06 07:27 UTC, GSemikozov approved these changes

2021-09-06 07:27 UTC, merged