add components, mockup
js-tasks-ru/htmlcss-20210812_boogie-woogie8 pull request #6
Opened 2021-08-19 19:01 UTC by ShakirovaAliya

2021-08-19 19:02 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-08-19 19:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-08-20 18:45 UTC, GSemikozov requested changes

2021-08-20 18:45 UTC, GSemikozov commented on components/footer/footer.css
> +    color: #212429;
наверное заберем из переменных?)

2021-08-20 18:45 UTC, GSemikozov commented on components/footer/footer.css
> +    width: 600px;
лучше все-таки max-width

2021-08-20 18:45 UTC, GSemikozov commented on components/header/header.css
> +    color: #212429;
и тут можно забрать из переменных

2021-08-20 18:45 UTC, GSemikozov commented on components/main/main.css
> +    height: 1036px;
фиксированную высоту можем убрать - в след ПР-е мы уже знаем как через флексбокс растянуть этот блок на все допустимое пространство

2021-08-20 18:47 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-08-20 18:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-08-20 18:56 UTC, ShakirovaAliya commented on components/footer/footer.css
> +    color: #212429;
забрала

2021-08-20 18:56 UTC, ShakirovaAliya commented on components/footer/footer.css
> +    width: 600px;
исправила

2021-08-20 18:56 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-08-20 18:56 UTC, ShakirovaAliya commented on components/header/header.css
> +    color: #212429;
забрала

2021-08-20 18:56 UTC, ShakirovaAliya commented on components/main/main.css
> +    height: 1036px;
убрала высоту

2021-08-21 09:53 UTC, GSemikozov approved these changes

2021-08-21 09:53 UTC, merged